### ISSUE TITLE
Use API platform and Messenger component 

### ISSUE THREAD

**Issue by damien-carcel** [damien-carcel/app-skeleton#143]
- [x] #79 - Solve the CORS issue when running fully on Docker
- [x] #144 - Replace the "Post" entity with a "User" entity
- [x] #145 - Switch the application to a command/query pattern
- [x] #146 - Add `akeneo/php-couplig-detector`
- [x] #194 - Use value objects in models
- [x] #147 - Handle commands and queries with Symfony Messenger component
- [x] #231 - Remove Doctrine ORM
- [x] #233 - Use Symfony Validator component
- [x] #148 - Install and configure API Platform
